### ISSUE TITLE
Content is not centered with small browser size

### ISSUE THREAD

**Issue by radiotaiso** [mgufrey/personal-webpage#2]
Found an issue where if the browser window is smaller than 1080 width the content is not centered and leaning to the right side of the window. 

We need to make it that it is always centered

Current:
![screen shot 2018-10-01 at 14 42 10](https://user-images.githubusercontent.com/20071246/46311554-38903880-c588-11e8-813b-f07df9151c09.png)

Expected:
<img width="947" alt="screen shot 2018-10-01 at 14 41 57" src="https://user-images.githubusercontent.com/20071246/46311559-3ded8300-c588-11e8-811b-b8df8e50950d.png">

**Comment by akashdakoor** [comment]
PR #6 fixes this issue
![screenshot_20181002_015606](https://user-images.githubusercontent.com/35390252/46313805-715efa80-c5e6-11e8-9049-a3279e9ed9ee.png)

**Comment by radiotaiso** [comment]
Fixed in #5 Thanks @ramonlsouza!

**Comment by radiotaiso** [comment]
Thank you @akashdakoor , we decided to go with Ramon's approach since we consider it a better fit, I will leave your PR open so it counts towards Hacktoberfest. Thank you for your time guys.
